on:
  push:
    branches:
      - govcloud
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module
